stages:
  - build_package

PackageBuild:
  stage: build_package
  image: python:latest
  tags:
   - exobuild1
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    # upload to gitlab pypi server
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    #upload to confluence server for distribution
    - TWINE_PASSWORD=${WIN10_UPLOAD_PASSWORD} TWINE_USERNAME=${WIN10_UPLOAD_USER} python -m twine upload --repository-url http://192.168.120.41:8080/ dist/*
  artifacts:
    untracked: false
    expire_in: 180 days
    paths:
      - "dist/*.tar.gz"
      - "dist/*.whl"
  only:
    - tags